version: '3.8'

services:
  client:
    build: client
    container_name: client
    ports:
      - '8080:8080'
    networks:
      - app-network

  server:
    build: server
    container_name: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=9da4571132ac98791f2d1a76a94eeb458c299ae172ad0d68b62d89fb3bcbe629c6a9afe8657bacbd5ee76c53d75724a06a436ba1db78d2cbc9571314ba839f91
      - MONGO_URI=mongodb://mongo:27017/mern_ecommerce # Default Mongo URL & DB name when running project locally
    ports:
      - '3000:3000'
    command: [
        'sh',
        '-c',
        'npm run seed:db admin@example.com admin123 && npm start'
      ] # Default email and password arguments to database seed script - update your admin email and password
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
